const NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY = process.env.NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY ?? "";
const NEXT_PUBLIC_SMTP_SERVER = process.env.NEXT_PUBLIC_SMTP_SERVER ?? "";
const NEXT_PUBLIC_SMTP_PORT = process.env.NEXT_PUBLIC_SMTP_PORT  ?? "";
const NEXT_PUBLIC_SMTP_USER = process.env.NEXT_PUBLIC_SMTP_USER  ?? "";
const NEXT_PUBLIC_SMTP_PASSWORD = process.env.NEXT_PUBLIC_SMTP_PASSWORD ?? "";
const NEXT_PUBLIC_IMAP_SERVER = process.env.NEXT_PUBLIC_IMAP_SERVER ?? "";
const NEXT_PUBLIC_IMAP_PORT = process.env.NEXT_PUBLIC_IMAP_PORT  ?? "";
const NEXT_PUBLIC_BASE_URL = process.env.NEXT_PUBLIC_BASE_URL  ?? "";
const NEXT_PUBLIC_DD_USER = process.env.NEXT_PUBLIC_DD_USER  ?? "";

export {
  NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY,
  NEXT_PUBLIC_SMTP_SERVER,
  NEXT_PUBLIC_SMTP_PORT,
  NEXT_PUBLIC_SMTP_USER,
  NEXT_PUBLIC_SMTP_PASSWORD,
  NEXT_PUBLIC_IMAP_SERVER,
  NEXT_PUBLIC_IMAP_PORT,
  NEXT_PUBLIC_BASE_URL,
  NEXT_PUBLIC_DD_USER
};
